# Generated by Django 6.1.1 on 2026-09-23 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('ativa', models.BooleanField(default=True)),
                ('monitores', models.ManyToManyField(blank=True, related_name='disciplinas_monitoradas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Duvida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('resposta', models.TextField(blank=True)),
                ('situacao', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ATENDIMENTO', 'Em atendimento'), ('RESPONDIDA', 'Respondida'), ('ENCERRADA', 'Encerrada')], default='ABERTA', max_length=20)),
                ('abertura_em', models.DateTimeField(auto_now_add=True)),
                ('atualizacao_em', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duvidas_abertas', to=settings.AUTH_USER_MODEL)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='duvidas', to='monitoria.disciplina')),
                ('monitor_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duvidas_assumidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-atualizacao_em',),
            },
        ),
    ]
